---
title: "Contacts"
editor: visual
---

Pour toute demande d'information concernant le parcours du master SEP, contacter :

### **Master Analyse et Politique Economique :**

**Emmanuelle GAUTHERAT**\
courriel : [emmanuelle.gautherat\@univ-reims.fr](mailto:emmanuelle.gautherat@univ-reims.fr)

**Coordonnées du secrétariat** :

courriel : [sesg.master-ape\@univ-reims.fr](mailto:sesg.master-ape@univ-reims.fr)\
Tel : 03.26.91.86.19

### **Master Mathématiques et Application :**

**Responsable du Master :**

Jules MAES\
courriel : [jules.maes\@univ-reims.fr](mailto:jules.maes@univ-reims.fr)

**Coordonnées du secrétariat** :

| courriel : [secretariat-math\@univ-reims.fr](mailto:secretariat-math@univ-reims.fr)
| Tel : 03.26.91.86.19

**Email du Master SEP :** [contact.mastersepreims\@gmail.com](http://mastersep.fr/contact.mastersepreims@gmail.com)

Vous souhaitez connaitre l'avis des étudiants sur l'enseignement dispensé et les possibles débouchées ? Posez votre question, les étudiants vous répondrons.

# 
